server:
  port: 7000

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  profiles:
    active: dev
    include: common
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/conerstone?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  #对于rabbitMQ的支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG

# TxManager Host Ip
tx-lcn:
  manager:
    host: 127.0.0.1
    # TxClient连接请求端口
    port: 8070
    # 心跳检测时间(ms)
    heart-time: 15000
    # 分布式事务执行总时间
    dtx-time: 30000
    concurrent-level: 128
  #参数延迟删除时间单位ms
  message:
    netty:
      attr-delay-time: 10000
  # 开启日志
  logger.enabled: true