#base:
#  security:
##    登录后返回内容的形式，json和重定向，json可以为返回的自定义内容
#    loginType: REDIRECT
#    permitUrls:
#      - /index
#    permitHtml:
#      - /login.html
#      - /home.html
#    permitStaticResource:
#      - /webjars/**
#      - /plugins/**
#      - /css/**
#      - /img/**
#      - /js/**
#      - /fonts/**
#      - /favicon.ico
#    rememberMe:
#      enable: false
#      firstStartUp: true
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mariadb://localhost:3306/conerstone?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#logging:
#  level:
#    com.cs.base: debug
